FROM python:3.12-slim

ENV DAGSTER_HOME=/app/dagster_home

RUN mkdir -p /app/dagster_home

RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean

# COPY dagster/requirements.txt .
# COPY dagster/docker/dagster.yaml /app/dagster_home/dagster.yaml
# COPY dagster/ETL /app

COPY requirements.txt .
# COPY dagster/docker/dagster.yaml /app/dagster_home/dagster.yaml
COPY dbt_dagster_redshift /app/dbt_dagster_redshift

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/dbt_dagster_redshift/weather_dagster

EXPOSE 3000

# CMD ["dagster-webserver", "-w", "workspace.yaml", "-h", "0.0.0.0", "-p", "3000"]


