FROM python:3.12-slim

ENV DAGSTER_HOME=/app/dagster_home
ENV DB_URL=postgresql://postgres:ha123@localhost:5432/postgres
ENV WEATHER_API_KEY=ca1013fef31f46529b260053242311
ENV WEATHER_API_URL=http://api.weatherapi.com/v1/current.json

RUN mkdir -p /app/dagster_home

RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean
    
WORKDIR /app

COPY dagster/requirements.txt .
COPY dagster/docker/dagster.yaml /app/dagster_home/dagster.yaml
COPY dagster/ETL /app
    
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3000

# CMD ["dagster-webserver", "-w", "workspace.yaml", "-h", "0.0.0.0", "-p", "3000"]


