services:
  dagster-web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: ["sh", "-c"]
    command: >
      "dagster dev -h 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    env_file:                      
      - .env
