-- models/weather_aqi_summary.sql
WITH weather_data AS (
    SELECT
        w.coord_lat,
        w.coord_lon,
        w.weather_id,
        w.weather_main,
        w.weather_description,
        w.weather_icon,
        w.base,
        w.temp,
        w.feels_like,
        w.temp_min,
        w.temp_max,
        w.pressure,
        w.humidity,
        w.sea_level,
        w.grnd_level,
        w.visibility,
        w.wind_speed,
        w.wind_deg,
        w.wind_gust,
        w.clouds_all,
        w.dt AS weather_dt,
        w.country,
        w.sunrise,
        w.sunset,
        w.timezone,
        w.id,
        w.name AS weather_name
    FROM {{ ref('weather_data') }} w
),
aqi_data AS (
    SELECT
        a.coord_lat,
        a.coord_lon,
        a.list_main_aqi,
        a.list_components_co,
        a.list_components_no,
        a.list_components_no2,
        a.list_components_o3,
        a.list_components_so2,
        a.list_components_pm2_5,
        a.list_components_pm10,
        a.list_components_nh3,
        a.dt AS aqi_dt
    FROM {{ ref('aqi_data') }} a
)
SELECT
    w.coord_lat,
    w.coord_lon,
    w.weather_main,
    w.weather_description,
    w.weather_icon,
    w.base,
    w.temp,
    w.feels_like,
    w.temp_min,
    w.temp_max,
    w.pressure,
    w.humidity,
    w.sea_level,
    w.grnd_level,
    w.visibility,
    w.wind_speed,
    w.wind_deg,
    w.wind_gust,
    w.clouds_all,
    weather_dt,
    w.country,
    w.sunrise,
    w.sunset,
    w.timezone,
    w.id,
    weather_name,
    a.list_main_aqi,
    a.list_components_co,
    a.list_components_no,
    a.list_components_no2,
    a.list_components_o3,
    a.list_components_so2,
    a.list_components_pm2_5,
    a.list_components_pm10,
    a.list_components_nh3,
    aqi_dt
FROM weather_data w
JOIN aqi_data a
    ON w.coord_lat = a.coord_lat
    AND w.coord_lon = a.coord_lon
